blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

blog/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
]

blog/main/models.py
from django.db import models

# Create your models here.

blog/main/views.py
from django.shortcuts import render


def main(request):
    '''
    Render the main page
    '''
    context = {'like':'Django 很棒'}
    return render(request, 'main/main.html', context)

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/main/templates/main /about.html
<!doctype html>
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
  </head>
  <body>
   {% include 'main/menu.html' %}
    <h2>關於部落格</h2>
    <p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
  </body>
</html>

blog/main/templates/main /main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
     <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
   {% include 'main/menu.html' %}
    <h2>Django 說 -- Hello world!</h2>
    <p>{{ like }}</p>
  </body>
</html>

blog/main/templates/main /menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
</ul>